config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome',to: 'static_pages#welcome',as: 'welcome'
  get 'about',to: 'static_pages#about',as: 'about'
  root to: redirect('/welcome',status: 302)
  post 'contact',to: 'static_pages#leave_feedback',as: 'leave_feedback'
  get 'contact',to:'static_pages#leave_feedback'

  #get 'mc_questions',to: 'mc_questions#index',as: 'mc_questions' #index
  #get 'mc_questions/new',to: 'mc_questions#new',as: 'new_mc_question' #new
  get 'mc_questions/:id',to: 'mc_questions#show',as: 'mc_question' #show
  #post 'mc_questions',to: 'mc_questions#create' #create
  get 'mc_questions/:id/edit',to: 'mc_questions#edit',as:'edit_mc_question' #edit
  patch 'mc_questions/:id',to: 'mc_questions#update' #update
  delete 'mc_questions/:id',to: 'mc_questions#destroy' #destroy

  get 'quizzes',to: 'quizzes#index',as: 'quizzes'
  get 'quizzes/:id',to: 'quizzes#show', as: 'quiz'
  get 'quizzes/:id/edit',to: 'quizzes#edit',as: 'edit_quiz'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id',to: 'quizzes#destroy'

  get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index',as: 'quiz_mc_questions'
  get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new',as: 'new_quiz_mc_question'
  post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create'

  get 'account/quizzes',to: 'account_quizzes#index',as: 'account_quizzes'
  get 'account/quizzes/new', to: 'account_quizzes#new', as: 'new_account_quiz'
  post 'account/quizzes', to: 'account_quizzes#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!,except: [:index , :show]
  before_action :require_permission,only: [:edit, :update, :destroy]

  def index
    quizzes = Quiz.includes(:user).all
    respond_to do |format|
      format.html{ render :index,locals: { quizzes: quizzes } }
    end
  end

  def show
    quiz = Quiz.find(params[:id])
    respond_to do |format|
      format.html{ render :show,locals: { quiz: quiz } }
    end
  end

#  def new
#    quiz = Quiz.new
#    respond_to do |format|
#      format.html{ render :new,locals: { quiz: quiz } }
#    end
#  end

#  def create
#    quiz = Quiz.new(quiz_params)
#    respond_to do |format|
#      format.html do
#        if quiz.save
#          flash[:success] = "Quiz saved successfully."
#          redirect_to quizzes_url
#        else
#          flash.now[:error] = "Error:Something Went Wrong!"
#          render :new,locals: { quiz: quiz }
#        end
#      end
#    end
#  end
  def require_permission
    if Quiz.find(params[:id]).user != current_user
      redirect_to quizzes_url,flash: { error: "You don't have permission to do that" }
    end
  end

  def edit
    quiz = Quiz.find(params[:id])
    respond_to do |format|
      format.html{ render :edit,locals: { quiz: quiz } }
    end
  end

  def update
    quiz = Quiz.find(params[:id])
    respond_to do |format|
      format.html do
        if quiz.update(quiz_params)
          flash[:success] = "Quiz updated successfully"
          redirect_to quizzes_url
        else
          flash.now[:error] = "Error: Something went Wrong!"
          render :edit,locals: { quiz: quiz }
        end
      end
    end
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy
    respond_to do |format|
      format.html do
        flash[:success] = "Quiz removed successfully"
        redirect_to quizzes_url
      end
    end
  end

  private
    def quiz_params
      params.require(:quiz).permit(:title,:description)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/edit.html.erb
<% provide(:title,"Edit Quiz") %>
<h1>Edit Quiz</h1>
<%= form_with model: quiz,url: quiz_path, method: :patch,local: true,scope: :quiz do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title,autofocus: true %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description,size: '12x7',class: "materialize-textarea" %>
  </div>
  <%= f.submit "Update Quiz",class: "btn waves-effect waves-light" %>
<% end %>

<br>
<br>
<br>

app/views/quizzes/index.html.erb
<% provide(:title,"Quizzes") %>

<div>
  <h1 class="blue-text center" style="font-weight:600">Quizzes</h1>
  <% quizzes.each do |quiz| %>
    <div id="<%= dom_id(quiz) %>">
      <br>
      <div class="card ">
        <div class="card-content blue">
          <div class="card-title">
              <strong><%= quiz.title %></strong>
              <span class="right">
                <%= link_to "🔎", quiz %>
                <% if quiz.user == current_user %>
                  <%= link_to "🖊️", edit_quiz_path(quiz),class: "link" %>
                  <%= link_to "🗑️",quiz,method: :delete,data: { confirm: "Are you sure?" } %>
                <% end %>
              </span>
          </div>
        </div>
        <div class="card-footer" style="padding:20px;">
          <p class="grey-text text-darken-2">
            Created by: <%= quiz.user.email %>
          </p>
          <p style="font-size:18px;">
            <%= truncate quiz.description,length: 75,separator: ' ' %>
          </p>

        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>

app/views/quizzes/show.html.erb
<% provide(:title,"Quiz #{quiz.id}") %>

<div class="card">
  <div class="card-container blue" style="padding:2px">
    <h3 class="white-text center"><%= quiz.title %></h3>
  </div>
  <div class="card-footer" style="padding:20px;">
    <p class="grey-text text-darken-2">
      Created by: <%= quiz.user.email %>
    </p>
    <p style="font-size:18px;"><%= quiz.description %></p>
  </div>
</div>

<h2 class="center blue-text">Questions</h2>

<% if quiz.user == current_user %>
  <p style="font-size:18px" class="center"><%= link_to "New Question" ,new_quiz_mc_question_path(quiz) %></p>
<% end %>
<br>
<div class="" style="padding-left:50px;">
  <% quiz.mc_questions.each do |question| %>
    <p style="font-size:18px">
      <%= question.question %>
      <%= link_to "🔍",question %>
      <% if question.quiz.user == current_user %>
        <%= link_to "🖋️",edit_mc_question_path(question) %>
        <%= link_to "🗑️", question ,method: :delete,data: { confirm: "Are you sure?" } %>
      <% end %>
    </p>
    <% choices = [question.answer,question.distractor_1] %>
    <% choices << question.distractor_2 if !question.distractor_2.blank? %>
    <% choices.each do |c| %>
      <div>
        <% if c == question.answer %>
          <p>
            <label>
                <input class="with-gap" name="<%= "guess_#{question.id}" %>" type="radio" disabled="disabled" checked />
                <span><%= c %></span>
            </label>
          </p>
        <% else %>
          <p>
            <label>
                <input class="with-gap" name="<%= "guess_#{question.id}" %>" type="radio" disabled="disabled" />
                <span><%= c %></span>
            </label>
          </p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<br>
<br>