config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome',to: 'static_pages#welcome',as: 'welcome'
  get 'about',to: 'static_pages#about',as: 'about'
  root to: redirect('/welcome',status: 302)
  post 'contact',to: 'static_pages#leave_feedback',as: 'leave_feedback'
  get 'contact',to:'static_pages#leave_feedback'

  #get 'mc_questions',to: 'mc_questions#index',as: 'mc_questions' #index
  #get 'mc_questions/new',to: 'mc_questions#new',as: 'new_mc_question' #new
  get 'mc_questions/:id',to: 'mc_questions#show',as: 'mc_question' #show
  #post 'mc_questions',to: 'mc_questions#create' #create
  get 'mc_questions/:id/edit',to: 'mc_questions#edit',as:'edit_mc_question' #edit
  patch 'mc_questions/:id',to: 'mc_questions#update' #update
  delete 'mc_questions/:id',to: 'mc_questions#destroy' #destroy

  get 'quizzes',to: 'quizzes#index',as: 'quizzes'
  get 'quizzes/:id',to: 'quizzes#show', as: 'quiz'
  get 'quizzes/:id/edit',to: 'quizzes#edit',as: 'edit_quiz'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id',to: 'quizzes#destroy'

  get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index',as: 'quiz_mc_questions'
  get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new',as: 'new_quiz_mc_question'
  post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create'

  get 'account/quizzes',to: 'account_quizzes#index',as: 'account_quizzes'
  get 'account/quizzes/new', to: 'account_quizzes#new', as: 'new_account_quiz'
  post 'account/quizzes', to: 'account_quizzes#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/quiz_mc_questions_controller.rb
class QuizMcQuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_permission,only: [:new, :create]
  def index
    quiz = Quiz.includes(:mc_questions).find(params[:id])
    respond_to do |format|
      format.html { render :index,locals: { quiz: quiz,questions: quiz.mc_questions } }
    end
  end

  def new
    quiz = Quiz.find(params[:id])
    respond_to do |format|
      format.html{ render :new,locals: { quiz: quiz,question: quiz.mc_questions.build } }
    end
  end

  def create
    quiz = Quiz.find(params[:id])
    question = quiz.mc_questions.build(question_params)

    respond_to do |format|
      format.html do
        if question.save
          flash[:success] = "Question saved successfully"
          redirect_to quiz_mc_questions_url
        else
          flash.now[:error] = "Something Went Wrong"
          render :new,locals: { quiz: quiz,question: quiz.mc_questions.build }
        end
      end
    end
  end

  def require_permission
    if Quiz.find(params[:id]).user != current_user
      redirect_to quizzes_url,flash: { error: "You don't have permission to do that" }
    end
  end


  private
    def question_params
      params.require(:mc_question).permit(:question,:answer,:distractor_1,:distractor_2)
    end
end

app/helpers/quiz_mc_questions_helper.rb
module QuizMcQuestionsHelper
end

app/views/quiz_mc_questions/index.html.erb
<% provide(:title,"Make Questions") %>
<h1>Multiple-Choice Questions</h1>
<%= link_to "Add Question", new_quiz_mc_question_path %>
<% questions.each do |question| %>
  <div>
    <p>
      <%= question.question %>
      <%= link_to "🔍",question %>
      <%= link_to "🖋️",edit_mc_question_path(question) %>
      <%= link_to "🗑️", question ,method: :delete,data: { confirm: "Are you sure?" } %>
    </p>
    <% choices = [question.answer,question.distractor_1,question.distractor_2] %>
    <% choices.each do |c| %>
      <div>
        <%= radio_button_tag "guess_#{question.id}",c,checked = c == question.answer,disabled: true %>
        <%= label_tag "guess_#{question.id}_#{c}",c %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/quiz_mc_questions/new.html.erb
<% provide(:title,"New Question") %>
<h1>New Question</h1>

<%= form_with model: question ,url: quiz_mc_questions_path(quiz),method: :post,local: true,scope: :mc_question do |f| %>
  <div>
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>
  <div>
    <%= f.label :answer %>
    <%= f.text_field :answer %>
  </div>
  <div>
    <%= f.label :distractor_1 %>
    <%= f.text_field :distractor_1 %>
  </div>
  <div>
    <%= f.label :distractor_2 %>
    <%= f.text_field :distractor_2 %>
  </div>
  <%= f.submit "Add Question" %>
<% end %>