config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome',to: 'static_pages#welcome',as: 'welcome'
  get 'about',to: 'static_pages#about',as: 'about'
  root to: redirect('/welcome',status: 302)
  post 'contact',to: 'static_pages#leave_feedback',as: 'leave_feedback'
  get 'contact',to:'static_pages#leave_feedback'

  #get 'mc_questions',to: 'mc_questions#index',as: 'mc_questions' #index
  #get 'mc_questions/new',to: 'mc_questions#new',as: 'new_mc_question' #new
  get 'mc_questions/:id',to: 'mc_questions#show',as: 'mc_question' #show
  #post 'mc_questions',to: 'mc_questions#create' #create
  get 'mc_questions/:id/edit',to: 'mc_questions#edit',as:'edit_mc_question' #edit
  patch 'mc_questions/:id',to: 'mc_questions#update' #update
  delete 'mc_questions/:id',to: 'mc_questions#destroy' #destroy

  get 'quizzes',to: 'quizzes#index',as: 'quizzes'
  get 'quizzes/:id',to: 'quizzes#show', as: 'quiz'
  get 'quizzes/:id/edit',to: 'quizzes#edit',as: 'edit_quiz'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id',to: 'quizzes#destroy'

  get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index',as: 'quiz_mc_questions'
  get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new',as: 'new_quiz_mc_question'
  post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create'

  get 'account/quizzes',to: 'account_quizzes#index',as: 'account_quizzes'
  get 'account/quizzes/new', to: 'account_quizzes#new', as: 'new_account_quiz'
  post 'account/quizzes', to: 'account_quizzes#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/account_quizzes_controller.rb
class AccountQuizzesController < ApplicationController
  before_action :authenticate_user!

  def index
    quizzes = current_user.quizzes

    respond_to do |format|
      format.html{ render :index,locals: { quizzes: quizzes } }
    end
  end

  def new
    # make empty quiz object
    quiz = Quiz.new
    # display new view
    respond_to do |format|
      format.html { render :new, locals: { quiz: quiz } }
    end
  end

  def create
    # new object from params
    quiz = current_user.quizzes.build(quiz_params)
    # respond_to block
    respond_to do |format|
      format.html do
        if quiz.save
          # success message
          flash[:success] = "Quiz saved successfully"
          # redirect to index
          redirect_to account_quizzes_url
        else
          # error message
          flash.now[:error] = "Error: Quiz could not be saved"
          # render new
          render :new, locals: { quiz: quiz }
        end
      end
    end
  end

  private
    def quiz_params
      params.require(:quiz).permit(:title,:description)
    end
end

app/helpers/account_quizzes_helper.rb
module AccountQuizzesHelper
end

app/views/account_quizzes/index.html.erb
<% provide(:title,"My Quizzes") %>
<h3 class="center blue-text" style="font-weight:600">My Quizzes</h3><br>
<p class="center blue-text" style="font-size:18px"><%= link_to "New Quiz" , new_account_quiz_path %></p>
<% quizzes.each do |quiz| %>
  <div id="<%= dom_id(quiz) %>">
    <br>
    <div class="card">
      <div class="card-content blue">
        <div class="card-title">
          <strong><%= quiz.title %></strong>
          <span class="right">
            <%= link_to '🔎', quiz_path(quiz) %>
            <%= link_to '🖋', edit_quiz_path(quiz) %>
            <%= link_to '🗑', quiz_path(quiz), method: :delete %>
          </span>
        </div>
      </div>
      <div class="card-footer" style="padding:10px">
        <p style="font-size:18px;">
          <%= quiz.description %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/account_quizzes/new.html.erb
<% provide(:title,"Create a New Quiz") %>
<h1>New Quiz</h1>
<%= form_with model: quiz,url: account_quizzes_path, method: :post,local: true,scope: :quiz do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title,autofocus: true %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description,size: '12x7',class: "materialize-textarea" %>
  </div>
  <%= f.submit "Add Quiz",class: "btn" %>
<% end %>