config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome',to: 'static_pages#welcome',as: 'welcome'
  get 'about',to: 'static_pages#about',as: 'about'
  root to: redirect('/welcome',status: 302)
  post 'contact',to: 'static_pages#leave_feedback',as: 'leave_feedback'
  get 'contact',to:'static_pages#leave_feedback'

  #get 'mc_questions',to: 'mc_questions#index',as: 'mc_questions' #index
  #get 'mc_questions/new',to: 'mc_questions#new',as: 'new_mc_question' #new
  get 'mc_questions/:id',to: 'mc_questions#show',as: 'mc_question' #show
  #post 'mc_questions',to: 'mc_questions#create' #create
  get 'mc_questions/:id/edit',to: 'mc_questions#edit',as:'edit_mc_question' #edit
  patch 'mc_questions/:id',to: 'mc_questions#update' #update
  delete 'mc_questions/:id',to: 'mc_questions#destroy' #destroy

  get 'quizzes',to: 'quizzes#index',as: 'quizzes'
  get 'quizzes/:id',to: 'quizzes#show', as: 'quiz'
  get 'quizzes/:id/edit',to: 'quizzes#edit',as: 'edit_quiz'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id',to: 'quizzes#destroy'

  get 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#index',as: 'quiz_mc_questions'
  get 'quizzes/:id/mc_questions/new', to: 'quiz_mc_questions#new',as: 'new_quiz_mc_question'
  post 'quizzes/:id/mc_questions', to: 'quiz_mc_questions#create'

  get 'account/quizzes',to: 'account_quizzes#index',as: 'account_quizzes'
  get 'account/quizzes/new', to: 'account_quizzes#new', as: 'new_account_quiz'
  post 'account/quizzes', to: 'account_quizzes#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMe | <%= yield(:title) %></title>
    <meta name="description" content="A Quiz app for the students of School and Universities.">
    <meta property="og:title" content="QuizMe: Explore our quizzes">
    <meta name="og:description" content="Free hand prebuild quizzes for the student of Colleges and Universities.">
    <meta name="og:image" content="quiz-bubble.png">

    <meta name="twitter:title" content="QuizMe: Explore our quizzes">
    <meta name="twitter:description" content="Free hand prebuild quizzes for the student of Colleges and Universities.">
    <meta name="twitter:image" content="quiz-bubble.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>


    <nav class="pink">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo" style="padding-left:10px;font-weight:600;">QuizMe!</a>
        <ul class="right" style="font-weight:bold;">
          <li><%= link_to "Home", welcome_path %></li>
          <li><%= link_to "Quizzes",quizzes_path %></li>
          <li><%= link_to "About",about_path %></li>
          <li><%= link_to "Contact",contact_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Hi, #{current_user.email}",edit_user_registration_path %></li>
            <li><%= link_to "My Quizzes",account_quizzes_path %></li>
            <li><%= link_to "Log out" ,destroy_user_session_path,method: :delete,class: "btn waves-effect waves-light blue" %></li>
          <% else %>
            <li><%= link_to "Sign In" ,new_user_session_path,class: "btn waves-effect waves-light blue" %></li>
            <li><%= link_to "Sign Up",new_user_registration_path,class:"btn waves-effect waves-light blue" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |key , message| %>
      <div class="alert card <%= flash_class(key) %> blue-text">
        <div class="card-content">
          <span><%= message %></span> <i id="alert_close" class="material-icons right" style="cursor:pointer;">close</i>
        </div>
      </div>
    <% end %>

    <div class="container">
        <div class="section">
          <%= yield %>
        </div>
    </div>

    <footer class="page-footer pink">
      <div class="container">
        <div class="row">
          <div class="col l6">
            <h3 class="white-text" style="font-weight:700">QuizMe</h3>
            <p class="white-text text-lighten-3" style="font-size:16px">QuizMe supports a variety of question styles like multiple choice and fill in the blank.</p>
          </div>
          <div class="col l4 offset-l2">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><%= link_to "Home", welcome_path,class: "grey-text text-lighten-4" %></li>
              <li><%= link_to "Quizzes",quizzes_path,class: "grey-text text-lighten-4" %></li>
              <li><%= link_to "About",about_path,class: "grey-text text-lighten-4" %></li>
              <li><%= link_to "Contact",leave_feedback_path,class: "grey-text text-lighten-4" %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col l12" style="padding-top: 20px; font-size: larger;">
                        Copyright © 2021.Debasish Mohanta
                        <div class="grey-text text-lighten-4 right" style="display: inline-block; font-size: larger;">
                            <a class="white-text" href="https://www.facebook.com/debasish.mohanta.52206" target="_blank" style="margin: 5px;"><i class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com/debasish__mohanta/" class="white-text" target="_blank" style="margin: 5px;"><i class="bi bi-instagram"></i></a>
                            <a href="https://www.linkedin.com/in/debasishmohanta/" class="white-text" target="_blank" style="margin: 5px;"><i class="bi bi-linkedin"></i></a>
                            <a href="" class="white-text" target="_blank" style="margin: 5px;"><i class="bi bi-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
      $('#alert_close').click(function(){
        $( ".alert" ).fadeOut( "slow", function() {
        });
      });
    </script>
  </body>
</html>